import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
import "react-toastify/dist/ReactToastify.css";
=======
;

>>>>>>> 976c5ced71fe28d0777e4c4e5d227e4d4cdb4a03
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar/>
        
        {children}
        <Footer />
      </body>
    </html>
  );
}
